# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NVDIMM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw', models.IntegerField(default='x')),
                ('lat', models.IntegerField(default='x')),
                ('iops', models.IntegerField(default='x')),
            ],
        ),
        migrations.CreateModel(
            name='NVME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw', models.IntegerField(default='x')),
                ('lat', models.IntegerField(default='x')),
                ('iops', models.IntegerField(default='x')),
            ],
        ),
    ]
